In [2]:
#lab01
'''
若是將python內建的list相乘，會得到一個list複製三次的結果
python_list= [1,2,3,4]                     
python_list = python_list*3     #複製3個python_list
print(python_list)

使用numpy宣告一個array，會將裡面的直接乘3

from numpy import *
a = array([1,2,3,4])       
a = a*3                 #內部矩陣相乘1*3 2*3 3*3 4*3
print (a)
'''

python_list= [1,2,3,4]
python_list = python_list*3
print(python_list)
print('------------------------')
from numpy import *
a = array([1,2,3,4])
a = a*3
print (a)



[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
------------------------
[ 3  6  9 12]


In [5]:
#lab02
'''
除了將值乘上一個數值，也可以將array相乘
from numpy import *
a = array([[1,2],[3,4]])
print(a)
a = a*a              #相對映位址互成[1 2] X  [1 2]  =[1 4]
                                  [3 4]    [3 4]   [9 16]
print(a)
'''

#from numpy import *
a = array([[1,2],[3,4]])
print(a)
print('------------------------')
a = a*a
print(a)



[[1 2]
 [3 4]]
------------------------
[[ 1  4]
 [ 9 16]]


In [6]:
#Lab03
'''
import numpy

#值皆為 0 的陣列
zeros_array = numpy.zeros((2,2))
print ('0 矩陣\n',zeros_array,end = '\n\n')

#值皆為 1 的陣列
ones_array = numpy.ones((2,2))
print ('1 矩陣\n',ones_array,end = '\n\n')

#值皆為 3 的陣列
full_array = numpy.full((2,2),3)
print ('3 矩陣\n',full_array,end = '\n\n')

#對角陣列
eye_array = numpy.eye(3,3)
print ('對角矩陣\n',eye_array,end = '\n\n')

#值皆為0-1間的亂數陣列
random_array = numpy.random.random((3,2))
print('亂數矩陣\n',random_array,end = '\n\n')

#產生1-9的亂數陣列
random_array = numpy.random.randint(1,10,(3,3))
print('亂數矩陣\n',random_array,end = '\n\n')
print('維度為:\n ',random_array.shape,end = '\n\n')
print('rank值:\n ',random_array.ndim,end = '\n\n')
print('陣列元素總數:\n ',random_array.size)

練習

使用
a = array([[1,3,5],[2,4,6],[3,5,7]])
取維度 rank 跟 元素個數

'''
import numpy

#值皆為 0 的陣列
zeros_array = numpy.zeros((2,2))
print ('0 矩陣\n',zeros_array,end = '\n\n')

#值皆為 1 的陣列
ones_array = numpy.ones((2,2))
print ('1 矩陣\n',ones_array,end = '\n\n')

#值皆為 3 的陣列
full_array = numpy.full((2,2),3)
print ('3 矩陣\n',full_array,end = '\n\n')

#對角陣列
eye_array = numpy.eye(3,3)
print ('對角矩陣\n',eye_array,end = '\n\n')

#值皆為0-1間的亂數陣列
random_array = numpy.random.random((3,2))
print('亂數矩陣\n',random_array,end = '\n\n')

#產生1-9的亂數陣列
random_array = numpy.random.randint(1,10,(3,3))
print('亂數矩陣\n',random_array,end = '\n\n')
print('維度為:\n ',random_array.shape,end = '\n\n')
print('rank值:\n ',random_array.ndim,end = '\n\n')
print('陣列元素總數:\n ',random_array.size)

0 矩陣
 [[ 0.  0.]
 [ 0.  0.]]

1 矩陣
 [[ 1.  1.]
 [ 1.  1.]]

3 矩陣
 [[3 3]
 [3 3]]

對角矩陣
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

亂數矩陣
 [[ 0.74668577  0.73816788]
 [ 0.30694501  0.24816988]
 [ 0.96521747  0.49823584]]

亂數矩陣
 [[2 6 8]
 [9 4 9]
 [1 3 4]]

維度為:
  (3, 3)

rank值:
  2

陣列元素總數:
  9


In [ ]:
'''
練習

使用
a = array([[1,3,5],[2,4,6],[3,5,7]])
取維度 rank 跟 元素個數

'''


In [5]:
#Lab04
'''
#arange(m,n-1,間隔)
第一個參數是起始值
第二個參數是最後值，但不包含
第三個參數是設定每個值間距，若無設定預設為1

#arrange(10, 30, 5).reshape( 2, 2 )
reshape的第一個參數為切幾列
reshape的第二個參數為切幾行
行列相乘的值需為元素總數


from numpy import *
array1 = arange(10,30,5)
print('使用arange產生的array1矩陣為:\n ',array1,end = '\n\n')
array1 = array1.reshape(4,1)
print('使用reshape切割後的array1矩陣為:\n ',array1)


練習:
使用arangey做出5*3值皆為奇數的陣列

'''
#from numpy import *
array1 = arange(10,30,5)
print('使用arange產生的array1矩陣為:\n ',array1,end = '\n\n')
array1 = array1.reshape(4,1)
print('使用reshape切割後的array1矩陣為:\n ',array1)

使用arange產生的array1矩陣為:
  [10 15 20 25]

使用reshape切割後的array1矩陣為:
  [[10]
 [15]
 [20]
 [25]]


In [ ]:
'''
練習:
使用arange(1,31,2)做出5*3值皆為奇數的陣列
'''


In [8]:
#Lab05
'''
from numpy import *

a = arange(1,4)
b = arange(2,8,2)

print('使用arange產生的a陣列與b陣列為:\n ',a,b,end = '\n\n')

#陣列相加
print('a陣列＋b陣列為:\n ',a+b,end = '\n\n')

#陣列 b 減 陣列 a
print('a陣列－b陣列為:\n ',b-a,end = '\n\n')

#陣列內相對應的位置之值做相乘
print('a陣列×b陣列為:\n ',a*b,end = '\n\n')

#陣列內相對應的位置之值做相除
print('a陣列／b陣列為:\n ',a/b)


練習

a = array([[2,3],[2,2]])
使用.eye產生1個對角矩陣及.ones產生1個單位矩陣，使其運算後與a的矩陣相等

'''
#from numpy import *

a = arange(1,4)
b = arange(2,8,2)

print('使用arange產生的a陣列與b陣列為:\n ',a,b,end = '\n\n')

#陣列相加
print('a陣列＋b陣列為:\n ',a+b,end = '\n\n')

#陣列 b 減 陣列 a
print('a陣列－b陣列為:\n ',b-a,end = '\n\n')

#陣列內相對應的位置之值做相乘
print('a陣列×b陣列為:\n ',a*b,end = '\n\n')

#陣列內相對應的位置之值做相除
print('a陣列／b陣列為:\n ',a/b)


使用arange產生的a陣列與b陣列為:
  [1 2 3] [2 4 6]

a陣列＋b陣列為:
  [3 6 9]

a陣列－b陣列為:
  [1 2 3]

a陣列×b陣列為:
  [ 2  8 18]

a陣列／b陣列為:
  [ 0.5  0.5  0.5]


In [2]:
'''
練習

a = array([[2,3],[2,2]])
使用.eye產生1個對角矩陣及.ones產生1個單位矩陣，使其運算後與a的矩陣相等

'''



'\n練習\n\na = array([[2,3],[2,2]])\n使用.eye產生1個對角矩陣及.ones產生1個單位矩陣，使其運算後與a的矩陣相等\n\n'

In [7]:
#Lab05-2
'''
from numpy import *
a=array([[5,0,2,3],[4,1,6,8]])
print('a矩陣為:\n ',a,end = '\n\n')

#陣列內值平方
print('a矩陣的平方為:\n ',a**2,end = '\n\n')

#陣列內值是否小於2
print ('a矩陣內值是平小於2:\n ',a<2,end = '\n\n')

print('a矩陣行的相加為:\n ',a.sum(axis=0),end = '\n\n')      #行的相加
print('a矩陣列的相加為:\n ',a.sum(axis=1),end = '\n\n')      #列的相加

print('取出a矩陣每行的最小值:\n ',a.min(axis=0),end = '\n\n') #取出每行的中最小值
print('取出a矩陣每列的最小值:\n ',a.min(axis=1),end = '\n\n') #取出每列的中最小值

print('取出a矩陣每行的最大值:\n ',a.max(axis=0),end = '\n\n') #取出每行的中最大值
print('取出a矩陣每列的最大值:\n ',a.max(axis=1))              #取出每列的中最大值

'''

#from numpy import *
a=array([[5,0,2,3],[4,1,6,8]])
print('a矩陣為:\n ',a,end = '\n\n')

#陣列內值平方
print('a矩陣的平方為:\n ',a**2,end = '\n\n')

#陣列內值是否小於2
print ('a矩陣內值是平小於2:\n ',a<2,end = '\n\n')

print('a矩陣行的相加為:\n ',a.sum(axis=0),end = '\n\n')      #行的相加
print('a矩陣列的相加為:\n ',a.sum(axis=1),end = '\n\n')      #列的相加

print('取出a矩陣每行的最小值:\n ',a.min(axis=0),end = '\n\n') #取出每行的中最小值
print('取出a矩陣每列的最小值:\n ',a.min(axis=1),end = '\n\n') #取出每列的中最小值

print('取出a矩陣每行的最大值:\n ',a.max(axis=0),end = '\n\n') #取出每行的中最大值
print('取出a矩陣每列的最大值:\n ',a.max(axis=1))              #取出每列的中最大值



a矩陣為:
  [[5 0 2 3]
 [4 1 6 8]]

a矩陣的平方為:
  [[25  0  4  9]
 [16  1 36 64]]

a矩陣內值是平小於2:
  [[False  True False False]
 [False  True False False]]

a矩陣行的相加為:
  [ 9  1  8 11]

a矩陣列的相加為:
  [10 19]

取出a矩陣每行的最小值:
  [4 0 2 3]

取出a矩陣每列的最小值:
  [0 1]

取出a矩陣每行的最大值:
  [5 1 6 8]

取出a矩陣每列的最大值:
  [5 8]


In [8]:
#Lab06
'''
from numpy import *

array1 = arange(1,5).reshape(2,2)
array1結果
[1 2]
[3 4]

array2 = arange(2,9,2).reshape(2,2)
array2結果
[2 4]
[6 8]

print('array1為:\n ',array1,'\n\n','array2為:\n ',array2,end = '\n\n')

print('array1與array2的內積為:\n',dot(array1,array2),end = '\n\n')  #內積
[1 2]  X  [2 4] = [1*2+2*6 1*4+2*8]
[3 4]     [6 8]   [3*2+4*6 3*4+4*8]

print('array1與array2的外積為:\n',cross(array1,array2),end = '\n\n') #外積
[2 4] =2x8-4x4   [2 1] =2x3-1x6
[4 8]            [6 3] 

print('array1的轉置矩陣為:\n',array1.T,end = '\n\n')                 #轉置矩陣
print('array2的轉置矩陣為:\n',array2.T)                              #轉置矩陣
'''

#from numpy import *

array1 = arange(1,5).reshape(2,2)
array2 = arange(2,9,2).reshape(2,2)

print('array1為:\n ',array1,'\n\n','array2為:\n ',array2,end = '\n\n')

print('array1與array2的內積為:\n',dot(array1,array2),end = '\n\n')  #內積
print('array1與array2的外積為:\n',cross(array1,array2),end = '\n\n') #外積

print('array1的轉置矩陣為:\n',array1.T,end = '\n\n')                 #轉置矩陣
print('array2的轉置矩陣為:\n',array2.T)                              #轉置矩陣

array1為:
  [[1 2]
 [3 4]] 

 array2為:
  [[2 4]
 [6 8]]

array1與array2的內積為:
 [[14 20]
 [30 44]]

array1與array2的外積為:
 [0 0]

array1的轉置矩陣為:
 [[1 3]
 [2 4]]

array2的轉置矩陣為:
 [[2 6]
 [4 8]]


In [9]:
#Lab07
'''
from numpy import *
x = arange(10)
print('x陣列為:\n ',x,end = '\n\n')

#取1,3,5值出來
x_135 = x[1:7:2]
print('x陣列位置1,3,5的值為:\n ',x_135,end = '\n\n')

#取 8,9 值出來
x_89 = x[-2:10]
print('x陣列位置8,9的值為:\n ',x_89,end = '\n\n')

#取 5到末值出來
x_5toend = x[5:]
print('x陣列位置5到最後的值為:\n ',x_5toend,end = '\n\n')

#將 x 切為兩等分
x = hsplit(x,2)
print('x陣列切割後為:\n ',x)


練習

a = array([1,1,2,3,5,8,13,21])
請取出 b = [2,5,13]
'''

#from numpy import *
x = arange(10)
print('x陣列為:\n ',x,end = '\n\n')

#取1,3,5值出來
x_135 = x[1:7:2]
print('x陣列位置1,3,5的值為:\n ',x_135,end = '\n\n')

#取 8,9 值出來
x_89 = x[-2:10]
print('x陣列位置8,9的值為:\n ',x_89,end = '\n\n')

#取 5到末值出來
x_5toend = x[5:]
print('x陣列位置5到最後的值為:\n ',x_5toend,end = '\n\n')

#將 x 切為兩等分
x = hsplit(x,2)
print('x陣列切割後為:\n ',x)

x陣列為:
  [0 1 2 3 4 5 6 7 8 9]

x陣列位置1,3,5的值為:
  [1 3 5]

x陣列位置8,9的值為:
  [8 9]

x陣列位置5到最後的值為:
  [5 6 7 8 9]

x陣列切割後為:
  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [ ]:
'''
練習

a = array([1,1,2,3,5,8,13,21])
請取出 b = [2,5,13]

'''


In [59]:
#Lab08
'''
#示範值若超過範圍，會無法顯示正確的值
a = array([1,2,3,129],dtype=int8)
print('a陣列的dtype為:\n ',a.dtype,end = '\n\n')
print('a陣列為:\n ',a)
'''

#示範值若超過範圍，會無法顯示正確的值
a = array([1,2,3,129],dtype=int8)
print('a陣列的dtype為:\n',a.dtype,end = '\n\n')
print('a陣列為:\n',a)

a陣列的dtype為:
  int8

a陣列為:
  [   1    2    3 -127]


In [65]:
#Lab09
'''
#matrix 的宣告示範
m = mat([[1,2],[3,4],[5,6]])
m[0,0] = 5
print('m矩陣的type為:',type(m),end = '\n\n')
print('m矩陣為:\n',m,end = '\n\n')

#array相乘
a = array([[1, 2], [3, 4]])
b = array([[5, 6], [7, 8]])
print ('array a * array b = \n', a * b,end = '\n\n')

#array內積
print ('dot(array a, array b) = \n', dot(a, b),end = '\n\n')

#matrix相乘
m1 = mat([[1, 2], [3, 4]])
m2 = mat([[5, 6], [7, 8]])
print('matrix m1 * matrix m2 = \n',m1*m2)
'''

#matrix 的宣告示範
m = mat([[1,2],[3,4],[5,6]])
m[0,0] = 5
print('m矩陣的type為:',type(m),end = '\n\n')
print('m矩陣為:\n',m,end = '\n\n')

#array相乘
a = array([[1, 2], [3, 4]])
b = array([[5, 6], [7, 8]])
print ('array a * array b = \n', a * b,end = '\n\n')

#array內積
print ('dot(array a, array b) = \n', dot(a, b),end = '\n\n')

#matrix相乘
m1 = mat([[1, 2], [3, 4]])
m2 = mat([[5, 6], [7, 8]])
print('matrix m1 * matrix m2 = \n',m1*m2)

m矩陣的type為: <class 'numpy.matrixlib.defmatrix.matrix'>

m矩陣為:
 [[5 2]
 [3 4]
 [5 6]]

array a * array b = 
 [[ 5 12]
 [21 32]]

dot(array a, array b) = 
 [[19 22]
 [43 50]]

matrix m1 * matrix m2 = 
 [[19 22]
 [43 50]]


In [11]:
#Lab10
'''
#matrix 操作練習
import numpy.matlib

#宣告一個 2*2，值皆為0的矩陣
zeros_matrix = numpy.matlib.zeros((2,2))
print('0 矩陣\n',zeros_matrix,end = '\n\n')

#宣告一個 2*2 ，值皆為1的矩陣
ones_matrix = numpy.matlib.ones ((2, 2))
print('1 矩陣\n',ones_matrix,end = '\n\n')

#宣告一個 2*2 的對角為1的矩陣
eye_matrix = numpy.matlib.eye(2)
print('對角矩陣\n',eye_matrix,end = '\n\n')

#宣告一個 2*2 的單位為1的矩陣
identity_matrix = numpy.matlib.identity(2)
print('單位矩陣\n',identity_matrix,end = '\n\n')

#將eye_matrix往直向複製兩次，橫向複製三次
repeat_matrix = numpy.matlib.repmat(eye_matrix,2,3)
print('複製\n',repeat_matrix,end = '\n\n')

#宣告一個 2*2 ，值介於0~1之間的亂數矩陣
random_matrix = numpy.matlib.rand ((2,2))
print('亂數矩陣\n',random_matrix,end = '\n\n')

#回傳一個standard normal的矩陣
standardrandom_matrix = numpy.matlib.randn(2,2)
print('常態分布亂數矩陣\n',standardrandom_matrix,end = '\n\n')

#宣告一個 2*2 的空矩陣
empty_matrix = numpy.matlib.empty((2,2))
print('空矩陣\n',empty_matrix)
'''

#matrix 操作練習
import numpy.matlib

#宣告一個 2*2，值皆為0的矩陣
zeros_matrix = numpy.matlib.zeros((2,2))
print('0 矩陣\n',zeros_matrix,end = '\n\n')

#宣告一個 2*2 ，值皆為1的矩陣
ones_matrix = numpy.matlib.ones ((2, 2))
print('1 矩陣\n',ones_matrix,end = '\n\n')

#宣告一個 2*2 的對角為1的矩陣
eye_matrix = numpy.matlib.eye(2)
print('對角矩陣\n',eye_matrix,end = '\n\n')

#宣告一個 2*2 的單位為1的矩陣
identity_matrix = numpy.matlib.identity(2)
print('單位矩陣\n',identity_matrix,end = '\n\n')

#將eye_matrix往直向複製兩次，橫向複製三次
repeat_matrix = numpy.matlib.repmat(eye_matrix,2,3)
print('複製\n',repeat_matrix,end = '\n\n')

#宣告一個 2*2 ，值介於0~1之間的亂數矩陣
random_matrix = numpy.matlib.rand ((2,2))
print('亂數矩陣\n',random_matrix,end = '\n\n')

#回傳一個standard normal的矩陣
standardrandom_matrix = numpy.matlib.randn(2,2)
print('常態分布亂數矩陣\n',standardrandom_matrix,end = '\n\n')

#宣告一個 2*2 的空矩陣
empty_matrix = numpy.matlib.empty((2,2))
print('空矩陣\n',empty_matrix)

0 矩陣
 [[ 0.  0.]
 [ 0.  0.]]

1 矩陣
 [[ 1.  1.]
 [ 1.  1.]]

對角矩陣
 [[ 1.  0.]
 [ 0.  1.]]

單位矩陣
 [[ 1.  0.]
 [ 0.  1.]]

複製
 [[ 1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.]]

亂數矩陣
 [[ 0.96115298  0.44128299]
 [ 0.91946615  0.34316923]]

常態分布亂數矩陣
 [[-1.25438973 -0.2429106 ]
 [-0.72995095 -0.06728894]]

空矩陣
 [[ 0.  0.]
 [ 0.  0.]]


In [12]:
#Lab11
'''
import numpy
x = matrix(arange(6).reshape((2, 3)))
print('矩陣x為:\n',x,end = '\n\n')
print('元素總和平均:',x.mean(),end = '\n\n')
print('每行平均:',x.mean(0),end = '\n\n')
print('每列平均:\n',x.mean(1))


練習
建立一個亂數矩陣
並算出元素總和平均值，每行平均及每列平均
'''

#import numpy
x = matrix(arange(6).reshape((2, 3)))
print('矩陣x為:\n',x,end = '\n\n')
print('元素總和平均:',x.mean(),end = '\n\n')
print('每行平均:',x.mean(0),end = '\n\n')
print('每列平均:\n',x.mean(1))

矩陣x為:
 [[0 1 2]
 [3 4 5]]

元素總和平均: 2.5

每行平均: [[ 1.5  2.5  3.5]]

每列平均:
 [[ 1.]
 [ 4.]]


In [ ]:
'''
練習
建立一個亂數矩陣
並算出元素總和平均值，每行平均及每列平均
'''
