EigenValue & EigenVector

In [5]:
import numpy as np
from scipy import linalg
A = np.array([[1,5,2],[2,4,1],[3,6,2]])
lna, v = linalg.eig(A)
l1, l2, l3 = lna
print(A)
#EigenValue
print('EigenValue')
print(l1, l2, l3)
print('------')
#EigenVector
print('EigenVector')
print(v)
print('-------')
print(v[:,0])
#print(v[:,1])
#print(v[:,2])
v1 = np.array(v[:,0]).T
print('-------')
print(v1)
print(A.dot(v1)-l1*v1)
print(linalg.norm(A.dot(v1)-l1*v1))

[[1 5 2]
 [2 4 1]
 [3 6 2]]
EigenValue
(7.95791620491+0j) (-1.25766470568+0j) (0.299748500767+0j)
------
EigenVector
[[-0.5297175  -0.90730751  0.28380519]
 [-0.44941741  0.28662547 -0.39012063]
 [-0.71932146  0.30763439  0.87593408]]
-------
[-0.5297175  -0.44941741 -0.71932146]
-------
[-0.5297175  -0.44941741 -0.71932146]
[ -2.66453526e-15+0.j  -4.44089210e-16+0.j  -1.77635684e-15+0.j]
3.233018248352212e-15
